version: '3.9'

services:
  app:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - database
    environment:
      - NODE_ENV=production
      - MONGO_HOST=mongodb://mongodb:27017/moto-academy 
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  database:
    container_name: mongodb

    build:
      context: ./database
      dockerfile: Dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data:
